/********************************************************************************
** Form generated from reading UI file 'regridparms.ui'
**
** Created: Thu Jun 12 13:29:43 2025
**      by: Qt User Interface Compiler version 4.8.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_REGRIDPARMS_H
#define UI_REGRIDPARMS_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDialog>
#include <QtGui/QDoubleSpinBox>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QSpinBox>

QT_BEGIN_NAMESPACE

class Ui_RegridParmsDialog
{
public:
    QLabel *label;
    QComboBox *cmaqgridComboBox;
    QLabel *label_2;
    QComboBox *regridmethodComboBox;
    QSpinBox *vgtypSpinBox;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QSpinBox *ncolsSpinBox;
    QSpinBox *nrowsSpinBox;
    QLabel *label_6;
    QSpinBox *gdtypSpinBox;
    QLabel *label_8;
    QLabel *label_10;
    QDoubleSpinBox *vgtopDSpinBox;
    QLabel *label_11;
    QDoubleSpinBox *ycellDSpinBox;
    QLabel *label_12;
    QDoubleSpinBox *xcellDSpinBox;
    QLabel *label_13;
    QDoubleSpinBox *yorigDSpinBox;
    QLabel *label_14;
    QDoubleSpinBox *xorigDSpinBox;
    QLabel *label_15;
    QSpinBox *nlaysSpinBox;
    QLabel *label_16;
    QLabel *label_7;
    QLabel *label_xOrig;
    QLabel *label_yOrig;
    QLabel *label_xCell;
    QLabel *label_yCell;
    QLabel *label_20;
    QDoubleSpinBox *palpDSpinBox;
    QLabel *label_21;
    QDoubleSpinBox *pbetDSpinBox;
    QLabel *label_22;
    QDoubleSpinBox *pgamDSpinBox;
    QLabel *label_23;
    QDoubleSpinBox *xcentDSpinBox;
    QLabel *label_24;
    QDoubleSpinBox *ycentDSpinBox;
    QLabel *label_25;
    QDoubleSpinBox *radiusDSpinBox;
    QLabel *label_26;
    QLabel *label_27;
    QDoubleSpinBox *gDSpinBox;
    QLabel *label_28;
    QDoubleSpinBox *rDSpinBox;
    QLabel *label_29;
    QDoubleSpinBox *p0DSpinBox;
    QLabel *label_30;
    QDoubleSpinBox *t0DSpinBox;
    QLabel *label_31;
    QDoubleSpinBox *aDSpinBox;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLineEdit *vglvlsLineEdit;
    QPushButton *acceptPushButton;
    QPushButton *cancelPushButton;
    QFrame *line;
    QPushButton *resetPushButton;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QComboBox *regridAggregationComboBox;
    QCheckBox *chk_userOverride;

    void setupUi(QDialog *RegridParmsDialog)
    {
        if (RegridParmsDialog->objectName().isEmpty())
            RegridParmsDialog->setObjectName(QString::fromUtf8("RegridParmsDialog"));
        RegridParmsDialog->resize(900, 400);
        RegridParmsDialog->setMinimumSize(QSize(900, 400));
        RegridParmsDialog->setMaximumSize(QSize(900, 470));
        label = new QLabel(RegridParmsDialog);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(24, 20, 91, 16));
        cmaqgridComboBox = new QComboBox(RegridParmsDialog);
        cmaqgridComboBox->setObjectName(QString::fromUtf8("cmaqgridComboBox"));
        cmaqgridComboBox->setGeometry(QRect(92, 16, 160, 24));
        cmaqgridComboBox->setMinimumSize(QSize(160, 24));
        cmaqgridComboBox->setMaximumSize(QSize(160, 24));
        label_2 = new QLabel(RegridParmsDialog);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(276, 20, 105, 16));
        regridmethodComboBox = new QComboBox(RegridParmsDialog);
        regridmethodComboBox->setObjectName(QString::fromUtf8("regridmethodComboBox"));
        regridmethodComboBox->setGeometry(QRect(372, 16, 160, 24));
        regridmethodComboBox->setMinimumSize(QSize(160, 24));
        regridmethodComboBox->setMaximumSize(QSize(160, 24));
        vgtypSpinBox = new QSpinBox(RegridParmsDialog);
        vgtypSpinBox->setObjectName(QString::fromUtf8("vgtypSpinBox"));
        vgtypSpinBox->setGeometry(QRect(84, 108, 120, 24));
        vgtypSpinBox->setMinimumSize(QSize(120, 24));
        vgtypSpinBox->setMaximumSize(QSize(120, 24));
        vgtypSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        vgtypSpinBox->setMinimum(1);
        vgtypSpinBox->setMaximum(7);
        label_3 = new QLabel(RegridParmsDialog);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(28, 84, 165, 16));
        label_4 = new QLabel(RegridParmsDialog);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(8, 112, 69, 16));
        label_5 = new QLabel(RegridParmsDialog);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(8, 136, 69, 16));
        ncolsSpinBox = new QSpinBox(RegridParmsDialog);
        ncolsSpinBox->setObjectName(QString::fromUtf8("ncolsSpinBox"));
        ncolsSpinBox->setGeometry(QRect(84, 132, 120, 24));
        ncolsSpinBox->setMinimumSize(QSize(120, 24));
        ncolsSpinBox->setMaximumSize(QSize(120, 24));
        ncolsSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        ncolsSpinBox->setMinimum(1);
        ncolsSpinBox->setMaximum(10000);
        nrowsSpinBox = new QSpinBox(RegridParmsDialog);
        nrowsSpinBox->setObjectName(QString::fromUtf8("nrowsSpinBox"));
        nrowsSpinBox->setGeometry(QRect(84, 156, 120, 24));
        nrowsSpinBox->setMinimumSize(QSize(120, 24));
        nrowsSpinBox->setMaximumSize(QSize(120, 24));
        nrowsSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        nrowsSpinBox->setMinimum(1);
        nrowsSpinBox->setMaximum(10000);
        label_6 = new QLabel(RegridParmsDialog);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(8, 160, 69, 16));
        gdtypSpinBox = new QSpinBox(RegridParmsDialog);
        gdtypSpinBox->setObjectName(QString::fromUtf8("gdtypSpinBox"));
        gdtypSpinBox->setGeometry(QRect(344, 108, 120, 24));
        gdtypSpinBox->setMinimumSize(QSize(120, 24));
        gdtypSpinBox->setMaximumSize(QSize(120, 24));
        gdtypSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        gdtypSpinBox->setMinimum(1);
        gdtypSpinBox->setMaximum(9);
        label_8 = new QLabel(RegridParmsDialog);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(268, 112, 69, 16));
        label_10 = new QLabel(RegridParmsDialog);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(8, 328, 69, 16));
        vgtopDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        vgtopDSpinBox->setObjectName(QString::fromUtf8("vgtopDSpinBox"));
        vgtopDSpinBox->setGeometry(QRect(84, 300, 120, 24));
        vgtopDSpinBox->setMinimumSize(QSize(120, 24));
        vgtopDSpinBox->setMaximumSize(QSize(120, 24));
        vgtopDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        vgtopDSpinBox->setMinimum(0);
        vgtopDSpinBox->setMaximum(1e+08);
        label_11 = new QLabel(RegridParmsDialog);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(8, 304, 69, 16));
        ycellDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        ycellDSpinBox->setObjectName(QString::fromUtf8("ycellDSpinBox"));
        ycellDSpinBox->setGeometry(QRect(84, 276, 120, 24));
        ycellDSpinBox->setMinimumSize(QSize(120, 24));
        ycellDSpinBox->setMaximumSize(QSize(120, 24));
        ycellDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        ycellDSpinBox->setDecimals(4);
        ycellDSpinBox->setMinimum(0.0001);
        ycellDSpinBox->setMaximum(1e+08);
        label_12 = new QLabel(RegridParmsDialog);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(8, 280, 69, 16));
        xcellDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        xcellDSpinBox->setObjectName(QString::fromUtf8("xcellDSpinBox"));
        xcellDSpinBox->setGeometry(QRect(84, 252, 120, 24));
        xcellDSpinBox->setMinimumSize(QSize(120, 24));
        xcellDSpinBox->setMaximumSize(QSize(120, 24));
        xcellDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        xcellDSpinBox->setDecimals(4);
        xcellDSpinBox->setMinimum(0.0001);
        xcellDSpinBox->setMaximum(1e+08);
        label_13 = new QLabel(RegridParmsDialog);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(8, 256, 69, 16));
        yorigDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        yorigDSpinBox->setObjectName(QString::fromUtf8("yorigDSpinBox"));
        yorigDSpinBox->setGeometry(QRect(84, 228, 120, 24));
        yorigDSpinBox->setMinimumSize(QSize(120, 24));
        yorigDSpinBox->setMaximumSize(QSize(120, 24));
        yorigDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        yorigDSpinBox->setDecimals(1);
        yorigDSpinBox->setMinimum(-1e+08);
        yorigDSpinBox->setMaximum(1e+08);
        label_14 = new QLabel(RegridParmsDialog);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(8, 232, 69, 16));
        xorigDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        xorigDSpinBox->setObjectName(QString::fromUtf8("xorigDSpinBox"));
        xorigDSpinBox->setGeometry(QRect(84, 204, 120, 24));
        xorigDSpinBox->setMinimumSize(QSize(120, 24));
        xorigDSpinBox->setMaximumSize(QSize(120, 24));
        xorigDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        xorigDSpinBox->setDecimals(1);
        xorigDSpinBox->setMinimum(-1e+08);
        xorigDSpinBox->setMaximum(1e+08);
        label_15 = new QLabel(RegridParmsDialog);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(8, 208, 69, 16));
        nlaysSpinBox = new QSpinBox(RegridParmsDialog);
        nlaysSpinBox->setObjectName(QString::fromUtf8("nlaysSpinBox"));
        nlaysSpinBox->setGeometry(QRect(84, 180, 120, 24));
        nlaysSpinBox->setMinimumSize(QSize(120, 24));
        nlaysSpinBox->setMaximumSize(QSize(120, 24));
        nlaysSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        nlaysSpinBox->setMinimum(1);
        nlaysSpinBox->setMaximum(100);
        label_16 = new QLabel(RegridParmsDialog);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(8, 184, 69, 16));
        label_7 = new QLabel(RegridParmsDialog);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(292, 84, 165, 16));
        label_xOrig = new QLabel(RegridParmsDialog);
        label_xOrig->setObjectName(QString::fromUtf8("label_xOrig"));
        label_xOrig->setGeometry(QRect(208, 208, 62, 16));
        label_yOrig = new QLabel(RegridParmsDialog);
        label_yOrig->setObjectName(QString::fromUtf8("label_yOrig"));
        label_yOrig->setGeometry(QRect(208, 232, 62, 16));
        label_xCell = new QLabel(RegridParmsDialog);
        label_xCell->setObjectName(QString::fromUtf8("label_xCell"));
        label_xCell->setGeometry(QRect(208, 256, 62, 16));
        label_yCell = new QLabel(RegridParmsDialog);
        label_yCell->setObjectName(QString::fromUtf8("label_yCell"));
        label_yCell->setGeometry(QRect(208, 280, 62, 16));
        label_20 = new QLabel(RegridParmsDialog);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(208, 304, 62, 16));
        palpDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        palpDSpinBox->setObjectName(QString::fromUtf8("palpDSpinBox"));
        palpDSpinBox->setGeometry(QRect(344, 132, 120, 24));
        palpDSpinBox->setMinimumSize(QSize(120, 24));
        palpDSpinBox->setMaximumSize(QSize(120, 24));
        palpDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        palpDSpinBox->setMinimum(-180);
        palpDSpinBox->setMaximum(180);
        label_21 = new QLabel(RegridParmsDialog);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(268, 136, 69, 16));
        pbetDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        pbetDSpinBox->setObjectName(QString::fromUtf8("pbetDSpinBox"));
        pbetDSpinBox->setGeometry(QRect(344, 156, 120, 24));
        pbetDSpinBox->setMinimumSize(QSize(120, 24));
        pbetDSpinBox->setMaximumSize(QSize(120, 24));
        pbetDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pbetDSpinBox->setMinimum(-180);
        pbetDSpinBox->setMaximum(180);
        label_22 = new QLabel(RegridParmsDialog);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(268, 160, 69, 16));
        pgamDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        pgamDSpinBox->setObjectName(QString::fromUtf8("pgamDSpinBox"));
        pgamDSpinBox->setGeometry(QRect(344, 180, 120, 24));
        pgamDSpinBox->setMinimumSize(QSize(120, 24));
        pgamDSpinBox->setMaximumSize(QSize(120, 24));
        pgamDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pgamDSpinBox->setMinimum(-180);
        pgamDSpinBox->setMaximum(180);
        label_23 = new QLabel(RegridParmsDialog);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(268, 184, 69, 16));
        xcentDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        xcentDSpinBox->setObjectName(QString::fromUtf8("xcentDSpinBox"));
        xcentDSpinBox->setGeometry(QRect(344, 204, 120, 24));
        xcentDSpinBox->setMinimumSize(QSize(120, 24));
        xcentDSpinBox->setMaximumSize(QSize(120, 24));
        xcentDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        xcentDSpinBox->setMinimum(-180);
        xcentDSpinBox->setMaximum(180);
        label_24 = new QLabel(RegridParmsDialog);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(268, 208, 69, 16));
        ycentDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        ycentDSpinBox->setObjectName(QString::fromUtf8("ycentDSpinBox"));
        ycentDSpinBox->setGeometry(QRect(344, 228, 120, 24));
        ycentDSpinBox->setMinimumSize(QSize(120, 24));
        ycentDSpinBox->setMaximumSize(QSize(120, 24));
        ycentDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        ycentDSpinBox->setMinimum(-90);
        ycentDSpinBox->setMaximum(90);
        label_25 = new QLabel(RegridParmsDialog);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(268, 232, 69, 16));
        radiusDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        radiusDSpinBox->setObjectName(QString::fromUtf8("radiusDSpinBox"));
        radiusDSpinBox->setGeometry(QRect(344, 252, 120, 24));
        radiusDSpinBox->setMinimumSize(QSize(120, 24));
        radiusDSpinBox->setMaximumSize(QSize(120, 24));
        radiusDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        radiusDSpinBox->setDecimals(0);
        radiusDSpinBox->setMinimum(1);
        radiusDSpinBox->setMaximum(1e+08);
        radiusDSpinBox->setValue(6.37e+06);
        label_26 = new QLabel(RegridParmsDialog);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(244, 256, 93, 16));
        label_27 = new QLabel(RegridParmsDialog);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(552, 84, 165, 16));
        gDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        gDSpinBox->setObjectName(QString::fromUtf8("gDSpinBox"));
        gDSpinBox->setGeometry(QRect(568, 108, 120, 24));
        gDSpinBox->setMinimumSize(QSize(120, 24));
        gDSpinBox->setMaximumSize(QSize(120, 24));
        gDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        gDSpinBox->setDecimals(2);
        gDSpinBox->setMaximum(9999);
        gDSpinBox->setValue(100);
        label_28 = new QLabel(RegridParmsDialog);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(492, 112, 69, 16));
        rDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        rDSpinBox->setObjectName(QString::fromUtf8("rDSpinBox"));
        rDSpinBox->setGeometry(QRect(568, 132, 120, 24));
        rDSpinBox->setMinimumSize(QSize(120, 24));
        rDSpinBox->setMaximumSize(QSize(120, 24));
        rDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        rDSpinBox->setMinimum(0);
        rDSpinBox->setMaximum(1e+08);
        label_29 = new QLabel(RegridParmsDialog);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(492, 136, 69, 16));
        p0DSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        p0DSpinBox->setObjectName(QString::fromUtf8("p0DSpinBox"));
        p0DSpinBox->setGeometry(QRect(568, 204, 120, 24));
        p0DSpinBox->setMinimumSize(QSize(120, 24));
        p0DSpinBox->setMaximumSize(QSize(120, 24));
        p0DSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        p0DSpinBox->setMinimum(-1e+08);
        p0DSpinBox->setMaximum(1e+08);
        label_30 = new QLabel(RegridParmsDialog);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(492, 208, 69, 16));
        t0DSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        t0DSpinBox->setObjectName(QString::fromUtf8("t0DSpinBox"));
        t0DSpinBox->setGeometry(QRect(568, 180, 120, 24));
        t0DSpinBox->setMinimumSize(QSize(120, 24));
        t0DSpinBox->setMaximumSize(QSize(120, 24));
        t0DSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        t0DSpinBox->setMinimum(0);
        t0DSpinBox->setMaximum(1e+08);
        label_31 = new QLabel(RegridParmsDialog);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(492, 184, 69, 16));
        aDSpinBox = new QDoubleSpinBox(RegridParmsDialog);
        aDSpinBox->setObjectName(QString::fromUtf8("aDSpinBox"));
        aDSpinBox->setGeometry(QRect(568, 156, 120, 24));
        aDSpinBox->setMinimumSize(QSize(120, 24));
        aDSpinBox->setMaximumSize(QSize(120, 24));
        aDSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        aDSpinBox->setMinimum(0);
        aDSpinBox->setMaximum(1e+08);
        label_32 = new QLabel(RegridParmsDialog);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(492, 160, 69, 16));
        label_33 = new QLabel(RegridParmsDialog);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(696, 112, 62, 16));
        label_34 = new QLabel(RegridParmsDialog);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(696, 136, 62, 16));
        label_35 = new QLabel(RegridParmsDialog);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(696, 160, 62, 16));
        label_36 = new QLabel(RegridParmsDialog);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(696, 184, 62, 16));
        label_37 = new QLabel(RegridParmsDialog);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(696, 208, 62, 16));
        vglvlsLineEdit = new QLineEdit(RegridParmsDialog);
        vglvlsLineEdit->setObjectName(QString::fromUtf8("vglvlsLineEdit"));
        vglvlsLineEdit->setGeometry(QRect(84, 324, 800, 24));
        vglvlsLineEdit->setMinimumSize(QSize(800, 24));
        vglvlsLineEdit->setMaximumSize(QSize(800, 24));
        acceptPushButton = new QPushButton(RegridParmsDialog);
        acceptPushButton->setObjectName(QString::fromUtf8("acceptPushButton"));
        acceptPushButton->setGeometry(QRect(568, 356, 92, 24));
        acceptPushButton->setMinimumSize(QSize(92, 24));
        acceptPushButton->setMaximumSize(QSize(92, 24));
        acceptPushButton->setAutoDefault(false);
        acceptPushButton->setDefault(false);
        cancelPushButton = new QPushButton(RegridParmsDialog);
        cancelPushButton->setObjectName(QString::fromUtf8("cancelPushButton"));
        cancelPushButton->setGeometry(QRect(356, 356, 92, 24));
        cancelPushButton->setMinimumSize(QSize(92, 24));
        cancelPushButton->setMaximumSize(QSize(92, 24));
        cancelPushButton->setAutoDefault(false);
        line = new QFrame(RegridParmsDialog);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(12, 68, 785, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        resetPushButton = new QPushButton(RegridParmsDialog);
        resetPushButton->setObjectName(QString::fromUtf8("resetPushButton"));
        resetPushButton->setGeometry(QRect(240, 356, 92, 24));
        resetPushButton->setMinimumSize(QSize(92, 24));
        resetPushButton->setMaximumSize(QSize(92, 24));
        resetPushButton->setAutoDefault(false);
        label_38 = new QLabel(RegridParmsDialog);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(468, 136, 37, 16));
        label_39 = new QLabel(RegridParmsDialog);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(468, 160, 37, 16));
        label_40 = new QLabel(RegridParmsDialog);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(468, 256, 37, 16));
        label_41 = new QLabel(RegridParmsDialog);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(468, 232, 37, 16));
        label_42 = new QLabel(RegridParmsDialog);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(468, 208, 37, 16));
        label_43 = new QLabel(RegridParmsDialog);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(468, 184, 37, 16));
        label_44 = new QLabel(RegridParmsDialog);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(552, 20, 105, 16));
        regridAggregationComboBox = new QComboBox(RegridParmsDialog);
        regridAggregationComboBox->setObjectName(QString::fromUtf8("regridAggregationComboBox"));
        regridAggregationComboBox->setGeometry(QRect(632, 16, 160, 24));
        regridAggregationComboBox->setMinimumSize(QSize(160, 24));
        regridAggregationComboBox->setMaximumSize(QSize(160, 24));
        chk_userOverride = new QCheckBox(RegridParmsDialog);
        chk_userOverride->setObjectName(QString::fromUtf8("chk_userOverride"));
        chk_userOverride->setGeometry(QRect(92, 48, 437, 17));
        QWidget::setTabOrder(cmaqgridComboBox, regridmethodComboBox);
        QWidget::setTabOrder(regridmethodComboBox, vgtypSpinBox);
        QWidget::setTabOrder(vgtypSpinBox, ncolsSpinBox);
        QWidget::setTabOrder(ncolsSpinBox, nrowsSpinBox);
        QWidget::setTabOrder(nrowsSpinBox, nlaysSpinBox);
        QWidget::setTabOrder(nlaysSpinBox, xorigDSpinBox);
        QWidget::setTabOrder(xorigDSpinBox, yorigDSpinBox);
        QWidget::setTabOrder(yorigDSpinBox, xcellDSpinBox);
        QWidget::setTabOrder(xcellDSpinBox, ycellDSpinBox);
        QWidget::setTabOrder(ycellDSpinBox, vgtopDSpinBox);
        QWidget::setTabOrder(vgtopDSpinBox, vglvlsLineEdit);
        QWidget::setTabOrder(vglvlsLineEdit, gdtypSpinBox);
        QWidget::setTabOrder(gdtypSpinBox, palpDSpinBox);
        QWidget::setTabOrder(palpDSpinBox, pbetDSpinBox);
        QWidget::setTabOrder(pbetDSpinBox, pgamDSpinBox);
        QWidget::setTabOrder(pgamDSpinBox, xcentDSpinBox);
        QWidget::setTabOrder(xcentDSpinBox, ycentDSpinBox);
        QWidget::setTabOrder(ycentDSpinBox, radiusDSpinBox);
        QWidget::setTabOrder(radiusDSpinBox, gDSpinBox);
        QWidget::setTabOrder(gDSpinBox, rDSpinBox);
        QWidget::setTabOrder(rDSpinBox, aDSpinBox);
        QWidget::setTabOrder(aDSpinBox, t0DSpinBox);
        QWidget::setTabOrder(t0DSpinBox, p0DSpinBox);
        QWidget::setTabOrder(p0DSpinBox, resetPushButton);
        QWidget::setTabOrder(resetPushButton, cancelPushButton);
        QWidget::setTabOrder(cancelPushButton, acceptPushButton);

        retranslateUi(RegridParmsDialog);

        QMetaObject::connectSlotsByName(RegridParmsDialog);
    } // setupUi

    void retranslateUi(QDialog *RegridParmsDialog)
    {
        RegridParmsDialog->setWindowTitle(QApplication::translate("RegridParmsDialog", "Regrid Parameters", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("RegridParmsDialog", "<b>CMAQ grid:", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Regrid method:</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p><span style=\" font-weight:600;\">CMAQ grid parameters</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">VGTYP:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">NCOLS:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">NROWS:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">GDTYP:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">VGLVLS:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">VGTOP</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">YCELL:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">XCELL:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">YORIG:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">XORIG:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">NLAYS:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p><span style=\" font-weight:600;\">CMAQ grid parameters</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_xOrig->setText(QApplication::translate("RegridParmsDialog", "m", 0, QApplication::UnicodeUTF8));
        label_yOrig->setText(QApplication::translate("RegridParmsDialog", "m", 0, QApplication::UnicodeUTF8));
        label_xCell->setText(QApplication::translate("RegridParmsDialog", "m", 0, QApplication::UnicodeUTF8));
        label_yCell->setText(QApplication::translate("RegridParmsDialog", "m", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("RegridParmsDialog", "Pa", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">P_ALP:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">P_BET:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">P_GAM:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">XCENT:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">YCENT:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">Earth Radius:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Constants</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">g:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">R:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">P0:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">T0:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p align=\"right\">A:</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("RegridParmsDialog", "m/s2", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("RegridParmsDialog", "J/kg/K", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("RegridParmsDialog", "K", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("RegridParmsDialog", "K", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("RegridParmsDialog", "Pa", 0, QApplication::UnicodeUTF8));
        acceptPushButton->setText(QApplication::translate("RegridParmsDialog", "Accept", 0, QApplication::UnicodeUTF8));
        cancelPushButton->setText(QApplication::translate("RegridParmsDialog", "Cancel", 0, QApplication::UnicodeUTF8));
        resetPushButton->setText(QApplication::translate("RegridParmsDialog", "Reset", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("RegridParmsDialog", "deg", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("RegridParmsDialog", "deg", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("RegridParmsDialog", "m", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("RegridParmsDialog", "deg", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("RegridParmsDialog", "deg", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("RegridParmsDialog", "deg", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("RegridParmsDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Aggregation:</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        chk_userOverride->setText(QApplication::translate("RegridParmsDialog", "Allow user override", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class RegridParmsDialog: public Ui_RegridParmsDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_REGRIDPARMS_H
